In [33]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import yaml
%matplotlib inline

try:
    with open("../config.yaml", "r") as file:
        config = yaml.safe_load(file)
except:
    print("Yaml configuration file not found!")

2. Loading Data

In [ ]:
config
#['data']['clean']['file_demo_experiment_cleaned']

In [ ]:
df_client = pd.read_csv(config['data']['raw']['file_client_profile'])
df_experiment = pd.read_csv(config['data']['raw']['file_experiment_clients'])
df_web1 = pd.read_csv(config['data']['raw']['file_web1'])
df_web2 = pd.read_csv(config['data']['raw']['file_web2'])
df_demo_experiment = pd.read_csv(config['data']['raw']['file_demo_experiment'])

In [ ]:
df_demo_experiment

In [ ]:
df_footprints = pd.concat([df_web1, df_web2])
df_footprints.to_csv(config['data']['raw']['file_footprints'])
df_footprints

3. Generic EDA

In [ ]:
df_client.info()

In [ ]:
df_client.head()
# df_client.isna().sum()
# df_client["gendr"].unique()
# df_client["bal"].min()
# df_client["bal"].max()

In [ ]:
df_client["calls_6_mnth"].unique()

In [ ]:
# df_client["num_accts"] =df_client["num_accts"].astype(int)

In [ ]:
df_experiment.head()

In [ ]:
df_experiment["Variation"].value_counts()
# df_experiment.dtypes
# df_experiment.isna().sum()

In [ ]:
df_footprints.info()
df_footprints.head()

In [ ]:
df_footprints["visitor_id"].nunique()

In [ ]:
# df_web1.head()
df_web1.info()
df_web1.duplicated().sum()

In [ ]:
# df_web2.head()
df_web2.info()
df_web2.duplicated().sum()

In [ ]:
# df_footprints["process_step"].unique()
# df_footprints["client_id"].value_counts()
# df_footprints["process_step"].unique()
df_footprints.isna().sum()

3a. df_client

In [ ]:
# df_client.info()
df_client.head()

In [ ]:
df_demo_experiment.info()
df_demo_experiment.head()

In [ ]:
Active = ['Test', 'Control']
test = df_demo_experiment[df_demo_experiment['variation'].isin(Active)]
test['clnt_age'].describe()

In [ ]:
test.head()

In [ ]:
test['clnt_tenure_yr'].describe()

In [ ]:
# sns.histplot(data=test,x=test["clnt_age"],y=test[""], )
sns.histplot(data=test["clnt_age"], kde=False, bins=10, color="salmon");

In [ ]:
sns.histplot(data=test["clnt_tenure_yr"], kde=False, bins=20, color="salmon");

In [ ]:
test["clnt_age"].value_counts().sort_values(ascending = False)

In [ ]:
test[test["clnt_age"]>35]

In [ ]:
df_client.select_dtypes("number").nunique().sort_values(ascending=False)

In [ ]:
df_client.select_dtypes("object").nunique().sort_values(ascending=False)

In [ ]:
potential_categorical_from_numerical = df_client.select_dtypes("number").loc[:, df_client.select_dtypes("number").nunique() < 20]
potential_categorical_from_numerical

In [ ]:
df_client["gendr"].value_counts()
# df_client.isna().sum()

In [ ]:
df_client["clnt_tenure_yr"].value_counts().sort_index(ascending=True)#.tail()
min_clnt_tenure_yr = df_client["clnt_tenure_yr"].min()
max_clnt_tenure_yr = df_client["clnt_tenure_yr"].max()
avg_clnt_tenure_yr = df_client["clnt_tenure_yr"].mean()
min_clnt_tenure_yr, max_clnt_tenure_yr

In [ ]:
df_client["clnt_tenure_mnth"].value_counts().sort_index(ascending=True)#.tail()

In [ ]:
df_client["clnt_age"].value_counts().sort_index(ascending=True)#.tail()

4. Clean

In [ ]:
# 
# df_demo_experiment.isna().sum()
# df1_demo.shape

In [ ]:
# Clean/rename columns
df_demo_experiment = df_demo_experiment.rename(columns = {"clnt_tenure_yr": "client_tenure_year", "clnt_tenure_mnth": "client_tenure_month", "clnt_age" : "client_age", "gendr": "gender", "bal": "balance","variation": "treatment_group"}).drop(columns = "Unnamed: 0")
df_demo_experiment.columns

In [ ]:
# df_demo_experiment.drop("Unnamed:\ 0")
df_demo_experiment

In [ ]:
# df_demo_experiment["client_tenure_year"].unique()

In [ ]:
# df_demo_experiment[df_demo_experiment["client_tenure_month"].isna()]
# df_demo_experiment.shape

In [ ]:
#Drop  row, when values in subset are null
df_demo_experiment = df_demo_experiment.dropna(subset = ["client_tenure_year", "client_tenure_month", "client_age"], how = "all" )
df_demo_experiment.shape

In [ ]:
df_demo_experiment = df_demo_experiment.dropna(subset = "treatment_group")
df_demo_experiment.info()

In [ ]:
df_demo_experiment["client_age"] = df_demo_experiment["client_age"].fillna(df_demo_experiment["client_age"].mean())
df_demo_experiment.isna().sum()

In [ ]:
def clean_gdr(x):
    gender = str(x)
    if gender == "X": 
        return "U"
    else:
        return x
    
df_demo_experiment["gender"] = df_demo_experiment["gender"].fillna("U")
# df_client["gendr"] = df_client["gendr"].apply(lambda x:"U" if x == "X" else x for x in df_client["gendr"])
df_demo_experiment["gender"] = df_demo_experiment["gender"].str.strip().apply(clean_gdr)
df_demo_experiment["gender"].unique()

In [ ]:
for col in ["client_tenure_year","client_tenure_month", "client_age", "num_accts","calls_6_mnth", "logons_6_mnth"]:
    df_demo_experiment[col] = df_demo_experiment[col].astype("int64")
df_demo_experiment.info()

In [ ]:
df_demo_experiment

In [45]:
# df_demo_experiment.to_csv(config['data']['clean']['file_demo_experiment_cleaned'],sep=",", index= False)
# df_demo_experiment.to_csv("../data/clean/df_final_demo_concat_cleaned_New.csv",sep=",", index= False)

In [ ]:
# df_demo_experiment["num_accts"].unique()
df_demo_experiment["treatment_group"].value_counts()

5.Transform

In [156]:
df_demo_experiment_old = pd.read_csv(config['data']['clean']['file_demo_experiment_cleaned'])
df_demo_experiment_old

,client_id,client_tenure_year,client_tenure_month,client_age,gender,num_accts,balance,calls_6_mnth,logons_6_mnth,variation
0,836976,6,73,60,U,2,45105.30,6,9,Test
1,2304905,7,94,58,U,2,110860.30,6,9,Control
2,1439522,5,64,32,U,2,52467.79,6,9,Test
3,1562045,16,198,49,M,2,67454.65,3,6,Test
4,5126305,12,145,33,F,2,103671.75,0,3,Control
...,...,...,...,...,...,...,...,...,...,...
50483,1780858,21,262,68,M,3,372100.59,6,9,Test
50484,6967120,21,260,68,M,3,4279873.38,6,9,Control
50485,5826160,20,249,56,F,2,44837.16,2,5,Test
50486,8739285,19,229,69,F,2,44994.24,1,4,Test
50487,7468138,18,222,61,F,3,209278.15,0,3,Test

In [ ]:
df_demo_experiment_old["variation"].value_counts()

In [161]:
df_footprints_cleaned = pd.read_csv(config['data']['clean']['footprint_final_client_experiment_Cleaned'])
df_footprints_cleaned

,client_id,visitor_id,visit_id,process_step,date_time,treatment_group
0,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:27:07,Test
1,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:26:51,Test
2,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:19:22,Test
3,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:19:13,Test
4,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:18:04,Test
...,...,...,...,...,...,...
317230,1574008,117364417_77840596075,528720790_71583064618_169151,start,2017-05-06 23:43:27,Test
317231,2908510,814969699_90652851448,562606085_36368381773_92090,start,2017-05-10 22:57:17,Control
317232,2908510,814969699_90652851448,562606085_36368381773_92090,step_2,2017-05-10 22:56:31,Control
317233,2908510,814969699_90652851448,562606085_36368381773_92090,step_1,2017-05-10 22:56:23,Control
317234,2908510,814969699_90652851448,562606085_36368381773_92090,start,2017-05-10 22:56:20,Control

In [ ]:
df_online = df_footprints_cleaned[df_footprints_cleaned.duplicated(['client_id','visitor_id','visit_id'],keep=False)]
df_online.shape
# df_online[df_online["client_id"] == 1336]

In [ ]:
df_online_test = df_footprints_cleaned[df_footprints_cleaned.duplicated(['client_id','visitor_id','visit_id'])]
df_online_test.shape
# df_online[df_online["client_id"] == 1336]

In [ ]:
# df_footprints_cleaned.duplicated(['client_id','visitor_id','visit_id'],keep=False).sum()
df_footprints_cleaned[df_footprints_cleaned["client_id"] == 9971962]

In [ ]:
df_online_test[df_online_test["client_id"] == 9971962]

In [ ]:
df_online[df_online["client_id"] == 9971962]

In [ ]:
df_not_online = df_footprints_cleaned[~df_footprints_cleaned.duplicated(subset = ["client_id","visitor_id", "visit_id" ],keep=False)]
df_not_online

In [ ]:
df_footprints_cleaned.shape[0] == df_online.shape[0] + df_not_online.shape[0]

In [67]:
df_online_sort = df_online.sort_values(by = ["client_id","date_time"], ascending= True)

In [ ]:
df_online_sort

In [69]:
df_online_sort["date_time"] = pd.to_datetime(df_online_sort["date_time"],errors="coerce")

In [70]:
df_online_sort["time_diff"] = df_online_sort.groupby(["client_id","visitor_id","visit_id"])["date_time"].transform(lambda x: x - x.iloc[0] if not x.isna().any() else pd.NA)
# df_online_sort.groupby(["client_id","visitor_id","visit_id"])["date_time"].agg({"timediff": lambda x: x - x.iloc[0]} )

In [ ]:
df_online_sort["time_diff"] = df_online_sort["time_diff"].dt.total_seconds()
df_online_sort

In [72]:
df_online_sort["time_diff_relative"] = df_online_sort.groupby(["client_id", "visitor_id", "visit_id"])["date_time"].diff().fillna(pd.Timedelta(0))

In [73]:
df_online_sort["time_diff_relative"] = df_online_sort["time_diff_relative"].dt.total_seconds()

In [74]:
df_online_sort["time_diff_percent"] = df_online_sort.groupby(["client_id","visitor_id","visit_id"])["time_diff"].transform(lambda x: round(x/x.iloc[-1],2) if not x.isna().any() else pd.NA)

In [ ]:
df_online_sort

In [ ]:
df_online_sort[df_online_sort["client_id"] == 9971962]

In [90]:
df_client_profile = pd.read_csv(config['data']['clean']['file_demo_experiment_cleaned'])

In [ ]:
df_client_profile= df_client_profile.rename(columns={"variation": "treament_group"})
df_client_profile.info()

In [79]:
df_online_sort_client_merge = pd.merge(df_online_sort,df_client_profile, on="client_id",how ="inner")

In [79]:
# df_online_sort_client_merge.to_csv(config['data']['clean']['file_footprints_transformed_client_merged'],sep=",", index= False)

In [ ]:
df_online_sort_client_merge

Filter out the process confirm with 0 timediff in seconds

In [152]:
df_online_sort_client_merge = pd.read_csv(config['data']['clean']['file_footprints_transformed_client_merged'])

In [158]:
df_online_sort_client_merge

,client_id,visitor_id,visit_id,process_step,date_time,treatment_group,time_diff,time_diff_relative,time_diff_percent,client_tenure_year,client_tenure_month,client_age,gender,num_accts,balance,calls_6_mnth,logons_6_mnth,treament_group,client_age_group
0,555,402506806_56087378777,637149525_38041617439_716659,start,2017-04-15 12:57:56,Test,0.0,0.0,0.00,3,46,29,U,2,25454.66,2,6,Test,young/adult
1,555,402506806_56087378777,637149525_38041617439_716659,step_1,2017-04-15 12:58:03,Test,7.0,7.0,0.04,3,46,29,U,2,25454.66,2,6,Test,young/adult
2,555,402506806_56087378777,637149525_38041617439_716659,step_2,2017-04-15 12:58:35,Test,39.0,32.0,0.25,3,46,29,U,2,25454.66,2,6,Test,young/adult
3,555,402506806_56087378777,637149525_38041617439_716659,step_3,2017-04-15 13:00:14,Test,138.0,99.0,0.87,3,46,29,U,2,25454.66,2,6,Test,young/adult
4,555,402506806_56087378777,637149525_38041617439_716659,confirm,2017-04-15 13:00:34,Test,158.0,20.0,1.00,3,46,29,U,2,25454.66,2,6,Test,young/adult
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
305734,9999729,834634258_21862004160,870243567_56915814033_814203,step_2,2017-05-08 16:08:40,Test,15.0,10.0,0.20,10,124,31,F,3,107059.74,6,9,Test,young/adult
305735,9999729,834634258_21862004160,870243567_56915814033_814203,step_3,2017-05-08 16:09:19,Test,54.0,39.0,0.72,10,124,31,F,3,107059.74,6,9,Test,young/adult
305736,9999729,834634258_21862004160,870243567_56915814033_814203,confirm,2017-05-08 16:09:40,Test,75.0,21.0,1.00,10,124,31,F,3,107059.74,6,9,Test,young/adult
305737,9999832,145538019_54444341400,472154369_16714624241_585315,start,2017-05-16 16:46:03,Test,0.0,0.0,0.00,23,281,49,F,2,431887.61,1,4,Test,middle-aged
305738,9999832,145538019_54444341400,472154369_16714624241_585315,step_1,2017-05-16 16:46:11,Test,8.0,8.0,1.00,23,281,49,F,2,431887.61,1,4,Test,middle-aged

In [153]:
import functions
df_online_sort_client_merge["client_age_group"] = df_online_sort_client_merge["client_age"].apply(functions.map_group_age)

In [ ]:
# df_online_sort_client_merge.to_csv("../data/clean/df_footprints_transformed_client_merged_New.csv",sep=",", index= False)

In [147]:
df_online_sort_client_merge = df_online_sort_client_merge[~((df_online_sort_client_merge["process_step"] == "confirm") & (df_online_sort_client_merge["time_diff"] == 0))]

In [148]:
df_online_sort_client_merge[df_online_sort_client_merge["treatment_group"] == "Control"]["time_diff"].describe()

count    134649.000000
mean        211.435748
std         508.246344
min           0.000000
25%          10.000000
50%          76.000000
75%         232.000000
max       41965.000000
Name: time_diff, dtype: float64

In [149]:
df_online_sort_client_merge[df_online_sort_client_merge["treatment_group"] == "Test"]["time_diff"].describe()

count    170086.000000
mean        233.719742
std         544.146166
min           0.000000
25%          10.000000
50%          86.000000
75%         247.000000
max       31624.000000
Name: time_diff, dtype: float64

In [ ]:
df_online_sort_client_merge["time_diff"].describe()

In [ ]:
df_online_sort_client_merge.isna().sum()

In [150]:
df_online_sort_client_merge[df_online_sort_client_merge["client_age"] < 35]["time_diff"].describe()

count    77331.000000
mean       170.656658
std        391.951918
min          0.000000
25%          7.000000
50%         61.000000
75%        181.000000
max      16901.000000
Name: time_diff, dtype: float64

In [151]:
df_online_sort_client_merge[df_online_sort_client_merge["client_age"] > 55]["time_diff"].describe()

count    112737.000000
mean        268.039020
std         535.706782
min           0.000000
25%          15.000000
50%         101.000000
75%         298.000000
max       15974.000000
Name: time_diff, dtype: float64

In [169]:
df_result = df_online_sort_client_merge.groupby(['client_id', 'visit_id', 'visitor_id']).apply(functions.calculate_error_rate).reset_index()

# Calculate avg error rate by treatment_group
avg_error_rates = df_result.groupby('treatment_group')['error_rate'].mean().reset_index()
avg_error_rates

AttributeError: module 'functions' has no attribute 'calculate_error_rate'

In [168]:
result

,client_id,visit_id,visitor_id,treatment_group,total_steps,backward_steps,error_rate
0,555,637149525_38041617439_716659,402506806_56087378777,Test,5,0,0.000000
1,647,40369564_40101682850_311847,66758770_53988066587,Test,5,0,0.000000
2,934,7076463_57954418406_971348,810392784_45004760546,Test,4,0,0.000000
3,1028,557292053_87239438319_391157,42237450_62128060588,Control,9,2,22.222222
4,1186,795373564_99931517312_810896,446844663_31615102958,Control,3,0,0.000000
...,...,...,...,...,...,...,...
58026,9999626,182723364_27031318473_880901,52633065_71189986073,Test,2,0,0.000000
58027,9999729,493310979_9209676464_421146,843385170_36953471821,Test,4,1,25.000000
58028,9999729,870243567_56915814033_814203,834634258_21862004160,Test,5,0,0.000000
58029,9999729,99583652_41711450505_426179,604429154_69247391147,Test,2,0,0.000000
58030,9999832,472154369_16714624241_585315,145538019_54444341400,Test,2,0,0.000000